// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozhueqptrfvbwvhzmlct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96aHVlcXB0cmZ2Ynd2aHptbGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTUwMTYsImV4cCI6MjA3MDczMTAxNn0.9-jYGz-B7XXN9zeUhefm8qOcitSKHRUhcdCUQxEj904";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});